# Generated by Django 4.2.7 on 2024-01-11 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_images')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Gallery',
                'db_table': 'gallery',
            },
        ),
        migrations.CreateModel(
            name='MenuGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'Menu groups',
                'verbose_name_plural': 'group',
                'db_table': 'menu_group',
            },
        ),
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='date and time')),
                ('name', models.CharField(max_length=50, verbose_name='client name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('guest', models.PositiveSmallIntegerField(verbose_name='guests number')),
                ('phone', models.PositiveBigIntegerField(verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Orders',
                'db_table': 'reservation',
            },
        ),
        migrations.CreateModel(
            name='TeamsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('job_title', models.CharField(max_length=50, verbose_name='job title')),
                ('image', models.ImageField(upload_to='team_images')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Your command',
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=250, verbose_name='description')),
                ('full_description', models.TextField(max_length=1200, verbose_name='full_description')),
                ('price', models.PositiveIntegerField(verbose_name='price($)')),
                ('image', models.ImageField(upload_to='menu_images', verbose_name='image')),
                ('specials', models.BooleanField(verbose_name='today special')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.menugroupmodel')),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Menu',
                'db_table': 'menu',
            },
        ),
    ]
